### ISSUE TITLE
Also support Gitlab / Gitlab CI

### ISSUE THREAD

**Issue by VolkerH** [haesleinhuepf/git-bob#378]
Hi git-bob,

can you rewrite yourself that you use the Gitlab-API vs the Github API?
This would be useful for code that is hosted on a private, self-hosted Gitlab instance.

git-bob solve

**Comment by haesleinhuepf** [comment]
git-bob what would be necessary to update in _github_utilities.py so that it supports gitlab instead of github?

git-bob comment

**Comment by haesleinhuepf** [comment]
How about the other functions in _github_utilities.py ? git-bob comment

**Comment by haesleinhuepf** [comment]
Are there functions in _github_utilities.py we haven't discussed yet? git-bob comment

**Comment by haesleinhuepf** [comment]
Ok cool. git-bob implement this in a new file _gitlab_utilities.py . Also add a new file to the tests directory which tests the functions similar to how we test the github utilities.

**Comment by haesleinhuepf** [comment]
Ok, everything above looks great! 

Next question: How would you implement the following functions in _gitlab_utilities.py, similar to the functions in _github_utilities.py but so that they use the gitlab API instead of the github api.

'copy_file_in_repository'
'download_to_repository'
'rename_file_in_repository'
'delete_file_from_repository'

git-bob think about this

**Comment by haesleinhuepf** [comment]
Ok, everything above looks great!

Next question: How would you implement the following functions in _gitlab_utilities.py, similar to the functions in _github_utilities.py but so that they use the gitlab API instead of the github api? No need to write tests for now.

* 'check_if_file_exists'
* 'write_file_in_branch'
* 'check_access_and_ask_for_approval'
* 'get_github_issue_details'
* 'get_contributors'
* 'get_conversation_on_issue'
* 'get_diff_of_pull_request'
* 'create_branch'
* 'get_diff_of_branches'
* 'add_reaction_to_last_comment_in_issue'
* 'add_reaction_to_issue'

git-bob solve

**Comment by haesleinhuepf** [comment]
git-bob think about this

**Comment by haesleinhuepf** [comment]
Ok, git-bob implement this in a new file _gitlab_utilities.py , but remove the `private_token` from all the functions and use `os.environ['GITLAB_API_KEY']` within `get_gitlab_repository` instead. Ensure that all functions in the newly created _gitlab_utilities.py have exactly the same signature like the functions in _github_utilities.py. Also make sure to implement all functions in _github_utilities.py . We need an identical API in _gitlab_utilities.py like in _github_utilities.py 

Also do not implement any tests yet.

git-bob solve
